[0m03:51:27.900612 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5232d92890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f52312d6320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f52312d62c0>]}


============================== 03:51:27.904552 | d44a99e5-10e6-4460-9a79-dea1b9f46b64 ==============================
[0m03:51:27.904552 [info ] [MainThread]: Running with dbt=1.7.8
[0m03:51:27.905255 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/idowuileks/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt init test_taxi', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m03:51:27.905840 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/home/idowuileks/.dbt')}
[0m03:51:27.906312 [info ] [MainThread]: Creating dbt configuration folder at 
[0m03:51:27.907283 [debug] [MainThread]: Starter project path: /home/idowuileks/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m03:51:27.909499 [info ] [MainThread]: 
Your new dbt project "test_taxi" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m03:51:27.909970 [info ] [MainThread]: Setting up your profile.
[0m03:51:27.910703 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m03:51:27.911753 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 0.013464424, "process_user_time": 1.999586, "process_kernel_time": 0.095788, "process_mem_max_rss": "91340", "process_in_blocks": "136", "process_out_blocks": "64", "command_success": false}
[0m03:51:27.912439 [debug] [MainThread]: Command `dbt init` failed at 03:51:27.912257 after 0.01 seconds
[0m03:51:27.912939 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5232d92890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f52312d63b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f52312d6320>]}
[0m03:51:27.913449 [debug] [MainThread]: Flushing usage events
[0m16:14:33.030912 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f12e6e868f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f12e53d2320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f12e53d2290>]}


============================== 16:14:33.033747 | ac149a05-6c98-42e2-b257-4c501220c017 ==============================
[0m16:14:33.033747 [info ] [MainThread]: Running with dbt=1.7.8
[0m16:14:33.034523 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/idowuileks/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt seed', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:14:33.035250 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/idowuileks/Desktop/tech_project/nyc_taxi_project/docker_sql/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:14:33.036235 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_wall_clock_time": 0.007753969, "process_user_time": 1.991438, "process_kernel_time": 0.067844, "process_mem_max_rss": "91396", "process_in_blocks": "8", "process_out_blocks": "16", "command_success": false}
[0m16:14:33.036971 [debug] [MainThread]: Command `dbt seed` failed at 16:14:33.036782 after 0.01 seconds
[0m16:14:33.037544 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f12e6e868f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f12e53d2bf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f12e53d2320>]}
[0m16:14:33.038216 [debug] [MainThread]: Flushing usage events
[0m16:14:52.305310 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fca6d0df9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fca6b626350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fca6b6262c0>]}


============================== 16:14:52.307819 | 40567a91-5e7a-45b3-8ec3-8b89ab9285b3 ==============================
[0m16:14:52.307819 [info ] [MainThread]: Running with dbt=1.7.8
[0m16:14:52.308450 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': './', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt seed --profiles-dir ./', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:14:52.309089 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/idowuileks/Desktop/tech_project/nyc_taxi_project/docker_sql/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:14:52.309965 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_wall_clock_time": 0.006862592, "process_user_time": 1.82593, "process_kernel_time": 0.092097, "process_mem_max_rss": "91652", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m16:14:52.310612 [debug] [MainThread]: Command `dbt seed` failed at 16:14:52.310436 after 0.01 seconds
[0m16:14:52.311108 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fca6d0df9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fca6b626d40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fca6b626350>]}
[0m16:14:52.311617 [debug] [MainThread]: Flushing usage events
[0m00:55:36.161446 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f618fa8a920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f618de77ac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f618de75840>]}


============================== 00:55:36.164169 | 4a69769b-f4e0-4e36-b4f2-b223225fbb95 ==============================
[0m00:55:36.164169 [info ] [MainThread]: Running with dbt=1.7.8
[0m00:55:36.164955 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': './ny-taxi-dbt/', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --profiles-dir ./ny-taxi-dbt/', 'send_anonymous_usage_stats': 'True'}
[0m00:55:36.165601 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/idowuileks/Desktop/tech_project/nyc_taxi_project/docker_sql/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:55:36.166485 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.04860476, "process_user_time": 1.893947, "process_kernel_time": 0.079577, "process_mem_max_rss": "92600", "process_in_blocks": "8", "process_out_blocks": "16", "command_success": false}
[0m00:55:36.167141 [debug] [MainThread]: Command `dbt run` failed at 00:55:36.166975 after 0.05 seconds
[0m00:55:36.167648 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f618fa8a920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f618de74c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f618de75870>]}
[0m00:55:36.168196 [debug] [MainThread]: Flushing usage events
[0m22:32:26.119959 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4b9b8de920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4b99c7f760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4b99c7f370>]}


============================== 22:32:26.122563 | 3ecd48aa-dcf3-4a07-ba61-31d4037a7a73 ==============================
[0m22:32:26.122563 [info ] [MainThread]: Running with dbt=1.7.8
[0m22:32:26.123197 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/idowuileks/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:32:49.027314 [debug] [MainThread]: Starter project path: /home/idowuileks/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m22:32:49.031295 [info ] [MainThread]: 
Your new dbt project "ny_taxi_test" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:32:49.031900 [info ] [MainThread]: Setting up your profile.
[0m22:33:23.566628 [info ] [MainThread]: Profile ny_taxi_test written to /home/idowuileks/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m22:33:23.567941 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 57.49155, "process_user_time": 1.937769, "process_kernel_time": 0.07608, "process_mem_max_rss": "96548", "process_in_blocks": "80", "process_out_blocks": "96"}
[0m22:33:23.568596 [debug] [MainThread]: Command `dbt init` succeeded at 22:33:23.568422 after 57.49 seconds
[0m22:33:23.569091 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4b9b8de920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4b996b9630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4b99c7ece0>]}
[0m22:33:23.569737 [debug] [MainThread]: Flushing usage events
[0m22:33:32.757044 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa2c1eeab90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa2c02cfaf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa2c02ced40>]}


============================== 22:33:32.759416 | e80c8185-f854-4f5d-aa18-8a058aa1387f ==============================
[0m22:33:32.759416 [info ] [MainThread]: Running with dbt=1.7.8
[0m22:33:32.760083 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/idowuileks/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:33:32.760776 [info ] [MainThread]: dbt version: 1.7.8
[0m22:33:32.761340 [info ] [MainThread]: python version: 3.10.12
[0m22:33:32.761822 [info ] [MainThread]: python path: /usr/bin/python3
[0m22:33:32.762315 [info ] [MainThread]: os info: Linux-6.5.0-21-generic-x86_64-with-glibc2.35
[0m22:33:32.936730 [info ] [MainThread]: Using profiles dir at /home/idowuileks/.dbt
[0m22:33:32.937373 [info ] [MainThread]: Using profiles.yml file at /home/idowuileks/.dbt/profiles.yml
[0m22:33:32.937916 [info ] [MainThread]: Using dbt_project.yml file at /home/idowuileks/Desktop/tech_project/nyc_taxi_project/docker_sql/dbt_project.yml
[0m22:33:32.938551 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m22:33:32.939585 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.22669421, "process_user_time": 2.133037, "process_kernel_time": 0.099674, "process_mem_max_rss": "100152", "process_in_blocks": "1296", "command_success": false, "process_out_blocks": "0"}
[0m22:33:32.940308 [debug] [MainThread]: Command `dbt debug` failed at 22:33:32.940112 after 0.23 seconds
[0m22:33:32.940869 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa2c1eeab90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa2c0209f30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa2c028b220>]}
[0m22:33:32.941455 [debug] [MainThread]: Flushing usage events
